# Generated by Django 5.1.4 on 2025-01-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_category_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_profile",
            field=models.ImageField(default="default.png", upload_to="profile_images/"),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
