# Generated by Django 5.1.4 on 2025-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_user_user_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
