# Generated by Django 5.1.4 on 2025-01-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
