# Generated by Django 5.1.4 on 2025-01-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_item_description_remove_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
