# Generated by Django 5.1.4 on 2025-01-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(max_length=50),
        ),
    ]
