# Generated by Django 5.1.4 on 2025-01-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
