# Generated by Django 5.1.4 on 2025-01-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
