# Generated by Django 5.1.4 on 2025-01-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_returneditem_user_alter_borroweditem_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borroweditem",
            name="activation",
        ),
        migrations.RemoveField(
            model_name="returneditem",
            name="activation",
        ),
    ]
